com/rbutti/pythoncrashcourse/chapter18/learning_log/learning_logs/urls.py
from django.urls import path

from . import views


app_name = 'learning_logs'

urlpatterns = [

    path('',views.index, name='index'),
    path('topics/',views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name= 'topic')
]

com/rbutti/pythoncrashcourse/chapter18/learning_log/learning_logs/views.py
from django.shortcuts import render
from .models import Topic

# Create your views here.

def index(request):
    return render(request, 'learning_logs/index.html')


def topics(request):
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

com/rbutti/pythoncrashcourse/chapter18/learning_log/learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'learning_logs:index' %}">Learning Log</a>
<a href="{% url 'learning_logs:topics' %}">Topics</a>
</p>
{% block content %}{% endblock content %}
</body>
</html>

com/rbutti/pythoncrashcourse/chapter18/learning_log/learning_logs/templates/learning_logs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'learning_logs/base.html'%}
{% block content %}
<p>Topic: {{ topic }}</p>

<p>Enteries</p>
<ul>
    {% for entry in entries %}
    <li>{{entry}}</li>
    {% empty %}
    <li>There are no entries for this topic yet.</li>
    {% endfor %}
</ul>

{% endblock content %}
</body>
</html>

com/rbutti/pythoncrashcourse/chapter18/learning_log/learning_logs/templates/learning_logs/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block content %}
<p>
    <ul>
    {% for topic in topics %}
    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
</ul>
</p>
{% endblock content %}
</body>
</html>